// SPDX-FileCopyrightText: 2026 Lytheriia
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Shared._Erida.PdaPainter;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client._Erida.PdaPainter;

[GenerateTypedNameReferences]
public sealed partial class PdaPainterWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public event Action<string>? OnPaintPda;
    public event Action<string>? OnApplyCard;
    public event Action<bool>? OnEject;

    public PdaPainterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PdaEjectButton.OnPressed += _ => OnEject?.Invoke(true);
        CardEjectButton.OnPressed += _ => OnEject?.Invoke(false);
    }

    public void UpdateState(PdaPainterBoundUserInterfaceState state)
    {
        var empty = Loc.GetString("pda-painter-empty");

        PdaNameLabel.Text = state.PdaName ?? empty;
        CardNameLabel.Text = state.CardName ?? empty;

        PdaEjectButton.Disabled = state.PdaName == null;
        CardEjectButton.Disabled = state.CardName == null;

        FillPresets(PdaPresetList, GetPresets(state.PdaPresets), state.PdaName != null, OnPaintPda);
        FillPresets(CardPresetList, GetPresets(state.CardPresets), state.CardName != null, OnApplyCard);
    }

    private List<EntityPrototype> GetPresets(
        HashSet<ProtoId<EntityPrototype>> presetIds)
    {
        var result = new List<EntityPrototype>();

        foreach (var id in presetIds)
        {
            if (_proto.TryIndex(id, out var proto))
                result.Add(proto);
        }

        result.Sort((a, b) =>
            string.Compare(a.Name, b.Name, StringComparison.CurrentCulture));

        return result;
    }
    private static void FillPresets(
        Control list,
        List<EntityPrototype> protos,
        bool enabled,
        Action<string>? onPressed)
    {
        list.RemoveAllChildren();

        foreach (var proto in protos)
        {
            var protoId = proto.ID;

            var icon = new EntityPrototypeView
            {
                Scale = new Vector2(2, 2),
                MinSize = new Vector2(48, 48),
                MouseFilter = MouseFilterMode.Ignore,
            };
            icon.SetPrototype(protoId);

            var button = new ContainerButton
            {
                StyleClasses = { ContainerButton.StyleClassButton },
                ToolTip = proto.Name,
                Disabled = !enabled,
                Children = { icon },
            };

            button.OnPressed += _ => onPressed?.Invoke(protoId);
            list.AddChild(button);
        }
    }
}

